import type { Command } from "commander";
import { input } from "@inquirer/prompts";
import { writeFile, mkdir } from "node:fs/promises";
import { join } from "node:path";

const API_INDEX_JS = `import { createServer } from "node:http";
import { createConnection } from "node:net";

const PORT = parseInt(process.env.PORT || "3000", 10);
const REDIS_URL = process.env.REDIS_URL || "redis://localhost:6379";

function redisPing() {
  return new Promise((resolve) => {
    const port = parseInt(new URL(REDIS_URL).port || "6379", 10);
    const host = new URL(REDIS_URL).hostname || "localhost";
    const socket = createConnection(port, host, () => socket.write("PING\\r\\n"));
    let data = "";
    socket.on("data", (chunk) => { data += chunk.toString(); socket.destroy(); });
    socket.on("close", () => resolve(data.includes("PONG")));
    socket.on("error", () => resolve(false));
    socket.setTimeout(2000, () => { socket.destroy(); resolve(false); });
  });
}

createServer(async (req, res) => {
  res.setHeader("Content-Type", "application/json");
  if (req.url === "/") {
    res.end(JSON.stringify({ status: "ok", service: "api" }));
  } else if (req.url === "/health") {
    const redisOk = await redisPing();
    res.writeHead(redisOk ? 200 : 503);
    res.end(JSON.stringify({ healthy: redisOk, redis: redisOk ? "connected" : "unreachable" }));
  } else {
    res.writeHead(404);
    res.end(JSON.stringify({ error: "not found" }));
  }
}).listen(PORT, () => console.log("API listening on port " + PORT));
`;

const WORKER_JS = `import { createConnection } from "node:net";

const REDIS_URL = process.env.REDIS_URL || "redis://localhost:6379";

function redisSet(key, value) {
  return new Promise((resolve) => {
    const port = parseInt(new URL(REDIS_URL).port || "6379", 10);
    const host = new URL(REDIS_URL).hostname || "localhost";
    const socket = createConnection(port, host, () => socket.write("SET " + key + " " + JSON.stringify(value) + "\\r\\n"));
    let data = "";
    socket.on("data", (chunk) => { data += chunk.toString(); socket.destroy(); });
    socket.on("close", () => resolve(data.includes("OK")));
    socket.on("error", () => resolve(false));
    socket.setTimeout(2000, () => { socket.destroy(); resolve(false); });
  });
}

console.log("Worker started");
let lastOk = false;
const heartbeat = setInterval(async () => {
  const ts = new Date().toISOString();
  const ok = await redisSet("worker:heartbeat", ts);
  if (ok !== lastOk) {
    console.log(ok ? "Redis connected" : "Redis unreachable");
    lastOk = ok;
  }
}, 5000);

function shutdown(signal) {
  console.log("Worker got " + signal + ", stopping");
  clearInterval(heartbeat);
  process.exit(0);
}
process.on("SIGTERM", () => shutdown("SIGTERM"));
process.on("SIGINT", () => shutdown("SIGINT"));
`;

export function registerInitCommand(program: Command): void {
  program
    .command("init")
    .description("Initialize a new workspace")
    .action(async () => {
      console.log("Creating a new workspace configuration...\n");

      const name = await input({ message: "Workspace name:", default: "my-workspace" });

      await mkdir("api", { recursive: true });
      await writeFile(join("api", "index.js"), API_INDEX_JS, "utf-8");
      await writeFile(join("api", "worker.js"), WORKER_JS, "utf-8");

      const yamlContent = `# workspace.yaml - ws workspace configuration
# Generated by ws init
#
# Services:
#   redis  - Redis container (port 6379), with TCP health check
#   api    - Node.js HTTP API (port 3000), connects to Redis
#   worker - Background heartbeat writer, depends on Redis
#
# Usage:
#   ws start              # start everything (redis first, then api + worker)
#   curl localhost:3000   # test the API
#   curl localhost:3000/health  # check Redis connectivity
#   ws stop               # graceful shutdown in reverse order

version: 1
name: "${name.replace(/"/g, '\\"')}"

services:
  redis:
    type: docker
    image: redis:7-alpine
    ports:
      - "6379:6379"
    health_check:
      type: tcp
      port: 6379
      interval: 2000
      timeout: 10000
    depends_on: []

  api:
    type: process
    workdir: ./api
    start: node index.js
    env:
      PORT: "3000"
      REDIS_URL: "redis://localhost:6379"
    depends_on:
      - redis

  worker:
    type: process
    workdir: ./api
    start: node worker.js
    env:
      REDIS_URL: "redis://localhost:6379"
    depends_on:
      - redis
`;

      await writeFile("workspace.yaml", yamlContent, "utf-8");
      console.log("\n✔ workspace.yaml created successfully!");
      console.log("  api/index.js  - HTTP API with Redis health check");
      console.log("  api/worker.js - Background worker with Redis heartbeat");
      console.log("\nRun 'ws start' to launch all services.");
    });
}
