import type { Command } from "commander";
import { input, confirm } from "@inquirer/prompts";
import { writeFile } from "node:fs/promises";

export function registerInitCommand(program: Command): void {
  program
    .command("init")
    .description("Initialize a new workspace")
    .action(async () => {
      console.log("Creating a new workspace configuration...\n");

      const name = await input({ message: "Workspace name:", default: "my-workspace" });

      const includeExample = await confirm({
        message: "Include an example service?",
        default: true,
      });

      const services: Record<string, unknown> = {};

      if (includeExample) {
        const exampleRepo = await input({
          message: "Example service Git repo URL (leave empty for a process-only service):",
          default: "",
        });

        services["example"] = {
          type: "process",
          ...(exampleRepo ? { repo: exampleRepo } : {}),
          start: "npm start",
        };
      }

      const config = {
        version: 1,
        name,
        services,
      };

      const yamlContent = `# workspace.yaml - ws workspace configuration
# Generated by ws init

version: ${config.version}
name: "${config.name.replace(/"/g, '\\"')}"

services:
${Object.entries(config.services)
  .map(
    ([key, val]) => {
      const svc = val as Record<string, string>;
      const lines = [`  ${key}:`, `    type: ${svc.type}`];
      if (svc.repo) lines.push(`    repo: ${svc.repo}`);
      lines.push(`    start: "${svc.start}"`);
      return lines.join("\n");
    },
  )
  .join("\n")}
`;

      await writeFile("workspace.yaml", yamlContent, "utf-8");
      console.log("\n✔ workspace.yaml created successfully!");
    });
}
